### ISSUE TITLE
issue with parsing lines

### ISSUE THREAD

**Issue by vks2106** [jerpint/whatsapp#1]
For below sample line

> 17/03/19, 9:24 am - User a: this is a sample line

the extract_msg(line) is not parsing correctly.

Below change worked for me.

` #datetime_pat  = "\d\d\d\d\-\d\d-\d\d\,\ \d\d\:\d\d" `

replaced by 

`datetime_pat  = r'(\d+/\d+/\d+)'`

**Comment by jerpint** [comment]
@vks2106 what phone are you doing the extraction from?

Mine was done on Android, and I recall hearing that the format of conversations might be different from iOS. Also perhaps WhatsApp has updated their format?

**Comment by jerpint** [comment]
I updated the post - hopefully should fix it - thanks!
